"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import projectionData from "@/data/site-projection.json";

type View = "state" | "cycles" | "physiology" | "projects" | "observation" | "strategy" | "service";
type ClosableCycle = { id: string; type: string; title: string; parent: string | null; evidencePolicy: "NOT_REQUIRED" };
type Cycle = {
  id: string; type: string; title: string; goal: string; cls: string; occurrence: number; state: "OPEN" | "CLOSED";
  decision: string; outcome: string; parent: string | null; result: string; step: string; plan: string[];
  evidencePolicy: string; evidence: string[]; schedule: { date: string } | null;
  experiment: null | { experimental_sku: string; control_sku: string };
};
type ObservationEvent = { id: string; date: string; occurredAt: string; type: "STATE_OBSERVED" | "CYCLE_CLOSED"; title: string; detail: string; cycle: string; evidence: string };
type Projection = {
  generatedAt: string; dataDate: string; counts: { total: number; open: number; closed: number }; currentCycle: Cycle;
  cycles: Cycle[]; events: ObservationEvent[]; currentStep: { status: string }[]; news: { title: string }[]; sourceRegistry: { sources: unknown[] };
};

const projection = projectionData as Projection;
const { cycles, events, currentCycle } = projection;
const dataDateLabel = new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${projection.dataDate}T00:00:00Z`));
const reviewDateLabel = currentCycle.schedule ? new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", timeZone: "UTC" }).format(new Date(`${currentCycle.schedule.date}T00:00:00Z`)) : "не назначена";

const navigation: { id: Exclude<View, "service">; index: string; label: string }[] = [
  { id: "state", index: "01", label: "Состояние" }, { id: "cycles", index: "02", label: "Циклы" },
  { id: "physiology", index: "03", label: "Физиология" }, { id: "projects", index: "04", label: "Проекты" },
  { id: "observation", index: "05", label: "Наблюдение" }, { id: "strategy", index: "06", label: "Стратегия" },
];

const operGroups = [
  { code: "A1–A2", name: "Спрос, ассортимент, каталог", count: 2, color: "orange" }, { code: "I1–I5", name: "Закупка и импорт", count: 5, color: "orange" },
  { code: "L(I)1–L(I)4", name: "Международная логистика", count: 4, color: "teal" }, { code: "L(R)1–L(R)7", name: "Логистика в России", count: 7, color: "teal" },
  { code: "S1–S3", name: "Продажи и возвраты", count: 3, color: "yellow" }, { code: "E1–E4", name: "Экономические gates", count: 4, color: "magenta" },
  { code: "O1–O5", name: "Наблюдение", count: 5, color: "blue" }, { code: "F1–F2", name: "Feedback", count: 2, color: "green" },
];
const values = [["VAL-01", "Натуральные / целлюлозные материалы"], ["VAL-02", "Яркость"], ["VAL-03", "Стиль"], ["VAL-04", "Комфорт"], ["VAL-05", "Дух свободы"], ["VAL-06", "Атмосфера солнечного Таиланда"], ["VAL-07", "Йога, нью-эйдж, вайб"]];
const projects = [
  { name: "Декларация 3Д", type: "REPAIR", state: "TERMINAL RESULT DEFINED", tone: "repair", purpose: "Восстановить compliance-контур для легального ввоза и торговли.", result: "Декларация получена, зарегистрирована, сохранена как evidence и принята OWNER_LPR.", gate: "Если декларация не активна, заказ новой партии и финансирование импорта со счёта проекта — HOLD.", refs: "EP-DP-DR-039 · EP-DP-DR-043" },
  { name: "Маркировка", type: "REPAIR", state: "ACTIVE_NOT_STABILIZED", tone: "repair", purpose: "Настроить и стабилизировать повторяемый marking workflow.", result: "ПО настроено; полный цикл выполнен без аварийных исправлений; результат принят и передан в L(R)2–L(R)4.", gate: "Кандидат ПО: «МойСклад». Передача в regular process запрещена до test pass.", refs: "EP-DP-DR-040 · EP-DP-DR-041" },
  { name: "Брендирование", type: "GROWTH", state: "PROJECT CARD DEFINED", tone: "growth", purpose: "Собрать целостное визуальное и смысловое представление бренда.", result: "Айдентика, логотип, упаковка, этикетки и карточки товара согласованы и приняты OWNER_LPR.", gate: "Рост уступает ремонту при конфликте ограниченного ресурса.", refs: "EP-DP-DR-042" },
];

function Evidence({ ids }: { ids: string[] | string }) { const list = Array.isArray(ids) ? ids : [ids]; return <div className="evidence">{list.map((id) => <span key={id}>{id}</span>)}</div>; }
function SectionHead({ index, kicker, title, copy }: { index: string; kicker: string; title: string; copy: string }) { return <header className="section-head"><div><p>{index} / {kicker}</p><h1>{title}</h1></div><p>{copy}</p></header>; }

export default function Home() {
  const [view, setView] = useState<View>("state");
  const [cycleFilter, setCycleFilter] = useState<"ALL" | "OPEN" | "CLOSED">("ALL");
  const [eventFilter, setEventFilter] = useState<"ALL" | "STATE_OBSERVED" | "CYCLE_CLOSED">("ALL");
  const [closingCycle, setClosingCycle] = useState<ClosableCycle | null>(null);
  const [closableCycles, setClosableCycles] = useState<ClosableCycle[]>([]);
  const [closableState, setClosableState] = useState<"loading" | "ready" | "auth" | "unconfigured" | "error">("loading");
  const [closureStatus, setClosureStatus] = useState<"idle" | "submitting" | "done" | "error">("idle");
  const [closureMessage, setClosureMessage] = useState("");
  const visibleCycles = useMemo(() => cycleFilter === "ALL" ? cycles : cycles.filter((cycle) => cycle.state === cycleFilter), [cycleFilter]);
  const visibleEvents = useMemo(() => eventFilter === "ALL" ? events : events.filter((event) => event.type === eventFilter), [eventFilter]);
  useEffect(() => {
    if (view !== "cycles") return;
    let active = true;
    fetch("/api/cycles/close", { headers: { accept: "application/json" } }).then(async (response) => {
      const body = await response.json().catch(() => ({})); if (!active) return;
      if (response.ok) { setClosableCycles(body.cycles || []); setClosableState("ready"); }
      else if (response.status === 401) setClosableState("auth"); else if (body.error === "INTEGRATION_NOT_CONFIGURED") setClosableState("unconfigured"); else setClosableState("error");
    });
    return () => { active = false; };
  }, [view]);
  const go = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submitClosure = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!closingCycle) return; const form = new FormData(event.currentTarget); setClosureStatus("submitting"); setClosureMessage("");
    const response = await fetch("/api/cycles/close", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ cycleId: closingCycle.id, outcome: form.get("outcome"), comment: form.get("comment") }) });
    const body = await response.json().catch(() => ({})); if (response.status === 401 && body.signIn) { window.location.assign(body.signIn); return; }
    if (!response.ok) { const labels: Record<string, string> = { INTEGRATION_NOT_CONFIGURED: "Запись в GitHub ещё не активирована.", EVIDENCE_REQUIRED: "Этот цикл нельзя закрыть без свидетельства.", OPEN_CHILD_CYCLES: "Сначала закройте открытые подциклы.", CYCLE_NOT_OPEN: "Цикл уже закрыт или изменён.", FORBIDDEN: "У этого аккаунта нет права закрывать циклы." }; setClosureStatus("error"); setClosureMessage(labels[body.error] || "GitHub не принял изменение. Обновите страницу и повторите попытку."); return; }
    setClosureStatus("done"); setClosureMessage(`Цикл закрыт. Событие ${body.eventId} записано в GitHub.`); setClosableCycles((items) => items.filter((item) => item.id !== closingCycle.id));
  };

  return <main>
    <header className="masthead"><button className="brand" onClick={() => go("state")} aria-label="На главную Elephant Pants"><span>EP</span><strong>Elephant Pants<small>бизнес-проект и философская машина</small></strong></button><nav aria-label="Основные разделы">{navigation.map((item) => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => go(item.id)}><i>{item.index}</i>{item.label}</button>)}</nav><div className="version">DATA · {projection.dataDate}</div></header>
    <div className="page-shell">
      {view === "state" && <section><SectionHead index="01" kicker="SYSTEM STATE" title="Состояние системы" copy="Текущее операционное состояние вычисляется из канонических CYCLE_RECORD и Observation events. Ручного параллельного статуса нет." />
        <div className="status-strip"><div><span>Система</span><strong>ACTIVE</strong></div><div><span>Физиология</span><strong>INTERNAL_QA</strong></div><div><span>Release</span><strong>NOT_RELEASED</strong></div><div><span>Циклы</span><strong>{projection.counts.open} OPEN · {projection.counts.closed} CLOSED</strong></div></div>
        <article className="focus-card"><div className="focus-kicker"><span>Текущий эксперимент</span><em>{currentCycle.state} / RUNNING</em></div><div className="focus-grid"><div><p className="mono">{currentCycle.id} · {currentCycle.type} · OCCURRENCE {currentCycle.occurrence}</p><h2>{currentCycle.goal}</h2><p className="lead">{currentCycle.result}</p>{currentCycle.experiment && <p><b>Эксперимент:</b> {currentCycle.experiment.experimental_sku} · <b>контроль:</b> {currentCycle.experiment.control_sku}</p>}</div><div className="next-action"><span>Текущий шаг</span><strong>{currentCycle.step.replaceAll("_", "_\u200b")}</strong><p>Сохранять эластичный бустинг 15% и остальные факторы без изменений. Следующая проверка — {reviewDateLabel}.</p><button onClick={() => go("cycles")}>Открыть цикл →</button></div></div><Evidence ids={currentCycle.evidence} /></article>
        <aside className="sales-path-card" aria-labelledby="sales-path-title"><div><span>Шпаргалка Ozon</span><h2 id="sales-path-title">Где посмотреть статистику продаж за неделю</h2></div><ol aria-label="Путь к аналитике продаж Ozon за последние 7 дней"><li>Цены и акции</li><li>Цены</li><li>Аналитика по продажам</li><li>Последние 7 дней</li></ol></aside>
        <div className="two-col"><section className="panel"><div className="panel-head"><span>Проектный контур</span><button onClick={() => go("projects")}>Все проекты →</button></div>{projects.map((project) => <div className="mini-row" key={project.name}><b>{project.name}</b><span>{project.type}</span><em>{project.state}</em></div>)}</section><section className="panel"><div className="panel-head"><span>Последние изменения</span><button onClick={() => go("observation")}>Весь журнал →</button></div>{events.slice(0, 4).map((event) => <div className="event-mini" key={event.id}><span>{event.id}</span><b>{event.title}</b><em>{event.type}</em></div>)}</section></div>
      </section>}

      {view === "cycles" && <section><SectionHead index="02" kicker="CYCLE REGISTER" title="Циклы" copy={`${projection.counts.total} экземпляров получены из канонических YAML: ${projection.counts.open} открыты, ${projection.counts.closed} закрыты.`} />
        <section className="closure-console"><div><span>Закрытие без свидетельств</span><h2>Доступные циклы</h2><p>Показываются только OPEN-циклы с явной политикой NOT_REQUIRED и без открытых подциклов.</p></div><div className="closable-list">{closableState === "loading" && <p>Проверяю GitHub…</p>}{closableState === "auth" && <a href="/signin-with-chatgpt?return_to=%2F">Войти с ChatGPT для управления →</a>}{closableState === "unconfigured" && <p>Запись в GitHub ещё не активирована.</p>}{closableState === "error" && <p>Не удалось получить актуальный список.</p>}{closableState === "ready" && closableCycles.length === 0 && <p>Сейчас нет циклов, которые разрешено закрыть без свидетельств.</p>}{closableCycles.map((cycle) => <article key={cycle.id}><div><span>{cycle.id} · {cycle.type}</span><strong>{cycle.title}</strong></div><button onClick={() => { setClosingCycle(cycle); setClosureStatus("idle"); setClosureMessage(""); }}>Закрыть</button></article>)}</div></section>
        <div className="filter-row" role="group" aria-label="Фильтр циклов">{(["ALL", "OPEN", "CLOSED"] as const).map((filter) => <button key={filter} className={cycleFilter === filter ? "selected" : ""} onClick={() => setCycleFilter(filter)}>{filter === "ALL" ? `Все · ${projection.counts.total}` : filter === "OPEN" ? `Открытые · ${projection.counts.open}` : `Закрытые · ${projection.counts.closed}`}</button>)}</div>
        <div className="cycle-list">{visibleCycles.map((cycle) => <article className={`cycle-card depth-${cycle.parent ? 1 : 0}`} key={cycle.id}><div className="cycle-line"><span className={`state ${cycle.state.toLowerCase()}`}>{cycle.state}</span><span>{cycle.cls}</span><span>occurrence {cycle.occurrence}</span><span>{cycle.outcome}</span></div><div className="cycle-body"><div><p className="mono">{cycle.id} · {cycle.type}</p><h2>{cycle.title}</h2>{cycle.parent && <p className="parent">↳ parent: {cycle.parent}</p>}</div><div><h3>Фактический результат</h3><p>{cycle.result}</p><h3>Текущий шаг</h3><p>{cycle.step}</p></div></div><div className="decision">transition_decision: <b>{cycle.decision}</b></div><Evidence ids={cycle.evidence} />{cycle.state === "OPEN" && <div className="cycle-close-row"><span>Закрытие на сайте: {cycle.evidencePolicy === "NOT_REQUIRED" ? "доступно в панели выше" : "требуется свидетельство"}.</span></div>}</article>)}</div>
        <section className="protocol-band"><div><span>Активные протоколы</span><h2>Повторяемая процедура вместо ручного статуса</h2></div><div><b>EP-DP-LOGISTICS-CYCLE-PROTOCOL-1.0</b><p>Регистрация и закрытие логистического дерева.</p><b>EP-DP-OZON-WEEKLY-SALES-REVIEW-PROTOCOL-1.0</b><p>Скриншот → проверка → эксперимент → решение → closure event.</p></div></section>
      </section>}

      {view === "physiology" && <section><SectionHead index="03" kicker="DOMAIN PHYSIOLOGY" title="Физиология" copy="EP-DP v0.2.1 опубликована как рабочий нормативный объект. Это INTERNAL_QA, а не выпущенный канон." /><div className="qa-banner"><div><span>EP-DP · 0.2.1</span><strong>INTERNAL_QA</strong></div><div><span>release_status</span><strong>NOT_RELEASED</strong></div><div><span>Oper lifecycle</span><strong>32 × CANDIDATE</strong></div><div><span>OpenItems</span><strong>30 RESOLVED · 4 OPEN</strong></div></div><section className="system-map"><div className="system-core"><img src="/machine-diagram-blue.png" alt="Схема регулярного товарного оборота Elephant Pants" /><div className="route"><b>A1/A2</b><i>→</i><b>Import</b><i>→</i><b>Logistic.Import</b><i>→</i><b>Logistic.Russia</b><i>→</i><b>Sales</b></div></div><div className="cross-control"><span>Поперечный орган</span><b>O. Observation</b><small>O1–O5 · классификация, запись, обновление, закрытие, обучение</small></div><div className="economic-control"><span>Контроль</span><b>E1–E4</b><small>launch · price · cashflow · reserve</small></div><div className="project-control"><span>Боковой контур</span><b>Repair / Growth</b><small>нестандартный дефект или новая способность</small></div></section><div className="phys-grid"><section><div className="subhead"><span>32 объекта</span><h2>Opers</h2></div><div className="oper-list">{operGroups.map((group) => <article key={group.code} className={`accent-${group.color}`}><strong>{group.code}</strong><b>{group.name}</b><span>{group.count} oper</span><em>CANDIDATE</em></article>)}</div></section><section><div className="subhead"><span>Поперечный маршрут</span><h2>Observation</h2></div><ol className="observation-route"><li><b>O1</b><span>Определить цикл действия</span></li><li><b>O2</b><span>Зарегистрировать новый цикл</span></li><li><b>O3</b><span>Обновить состояние открытого</span></li><li><b>O4</b><span>Зафиксировать closure или reopening</span></li><li><b>O5</b><span>Изменить протокол по значимому evidence</span></li></ol></section></div><section className="values"><div className="subhead"><span>VALUE FILTER</span><h2>Семь ценностей</h2><p>Норматив выбора, а не автоматически подтверждённое свойство товара.</p></div><div>{values.map(([id, name]) => <article key={id}><span>{id}</span><b>{name}</b><em>CANDIDATE</em></article>)}</div></section></section>}

      {view === "projects" && <section><SectionHead index="04" kicker="PROJECT CONTOUR" title="Проекты" copy="Разовые циклы отделены от регулярной торговли. REPAIR получает приоритет над GROWTH при конфликте ограниченного ресурса; лимит WIP — два активных проекта." /><div className="project-list">{projects.map((project, index) => <article key={project.name} className={project.tone}><div className="project-no">0{index + 1}</div><div className="project-main"><div className="project-meta"><span>{project.type}</span><em>{project.state}</em></div><h2>{project.name}</h2><p className="lead">{project.purpose}</p><div className="project-grid"><div><h3>Terminal result</h3><p>{project.result}</p></div><div><h3>Gate / handoff</h3><p>{project.gate}</p></div></div><Evidence ids={project.refs} /></div></article>)}</div></section>}

      {view === "observation" && <section><SectionHead index="05" kicker="OBSERVATION LOG" title="Наблюдение" copy="Append-only журнал событий. Публичная проекция строится непосредственно из YAML и не раскрывает исходные файлы." /><div className="filter-row" role="group" aria-label="Фильтр событий">{(["ALL", "STATE_OBSERVED", "CYCLE_CLOSED"] as const).map((filter) => <button key={filter} className={eventFilter === filter ? "selected" : ""} onClick={() => setEventFilter(filter)}>{filter === "ALL" ? `Все · ${events.length}` : filter}</button>)}</div><div className="timeline">{visibleEvents.map((event) => <article key={event.id}><div className="time-mark"><span>{event.date}</span><i /></div><div><div className="event-meta"><span>{event.type}</span><em>{event.cycle}</em></div><p className="mono">{event.id}</p><h2>{event.title}</h2><p>{event.detail}</p><div className="evidence-description"><span>Evidence</span><b>{event.evidence}</b></div></div></article>)}</div></section>}

      {view === "strategy" && <section><SectionHead index="06" kicker="STRATEGY" title="Стратегия" copy="Текущий горизонт автоматически следует за открытым датированным циклом; долгосрочные ориентиры остаются отдельным слоем." /><div className="roadmap"><article className="current"><span>Сейчас</span><div><em>ACTIVE HORIZON</em><h2>{currentCycle.goal}</h2><p>{currentCycle.result}</p><ul>{currentCycle.plan.map((step) => <li key={step}>{step}</li>)}</ul></div></article><article><span>До 6 месяцев</span><div><em>NEXT</em><h2>Рабочие правила повторения</h2><p>Подтвердить цену, ассортимент, маркировку, упаковку и регулярную логистику на сопоставимых данных.</p></div></article><article><span>Около 2 лет</span><div><em>DIRECTION</em><h2>Каналы и устойчивая поставка</h2><p>Развивать каналы продаж и устойчивость поставки после восстановления детального плана и критериев перехода.</p></div></article><article><span>2031–2033</span><div><em>LONG-TERM</em><h2>Федеральная многоканальная система</h2><p>Маркетплейсы, DTC, опт и региональные партнёры: 20 000+ пар в год, 100+ оптовых клиентов и устойчивый бренд категории.</p></div></article></div></section>}

      {view === "service" && <section><SectionHead index="00" kicker="SERVICE" title="Служебный раздел" copy="Метаданные публичной проекции и состояние связи с источником истины." /><div className="service-grid"><article><span>Проекция</span><strong>AUTO</strong><p>Циклы, события и текущий шаг генерируются из канонических данных.</p></article><article><span>Доменная физиология</span><strong>EP-DP v0.2.1</strong><p>INTERNAL_QA / NOT_RELEASED</p></article><article><span>Данные обновлены</span><strong>{dataDateLabel}</strong><p>{projection.news.at(-1)?.title}</p></article><article><span>Источники / задачи</span><strong>{projection.sourceRegistry.sources.length} / {projection.currentStep.length}</strong><p>JSON-слои также включены в проверяемую проекцию.</p></article></div><div className="history"><h2>История сайта</h2><article><time>{projection.dataDate}</time><div><b>Data-driven projection</b><p>UI больше не хранит копию cycles, events и current state в page.tsx.</p></div></article><article><time>08.08.2026</time><div><b>Доменная миграция</b><p>Состояние, циклы, физиология, проекты и Observation заменили старые ручные страницы и статусы.</p></div></article></div><a className="repo-link" href="https://github.com/valerol/ep_dashboard" target="_blank" rel="noreferrer">Открыть valerol/ep_dashboard →</a></section>}
    </div>

    {closingCycle && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setClosingCycle(null)}><section className="closure-modal" role="dialog" aria-modal="true" aria-labelledby="closure-title"><button className="modal-close" onClick={() => setClosingCycle(null)} aria-label="Закрыть окно">×</button><p className="mono">{closingCycle.id}</p><h2 id="closure-title">Закрыть цикл</h2><p>{closingCycle.title}</p><form onSubmit={submitClosure}><label>Результат<select name="outcome" defaultValue="ACHIEVED" required><option value="ACHIEVED">ACHIEVED</option><option value="PARTIAL">PARTIAL</option><option value="FAILED">FAILED</option><option value="CANCELLED">CANCELLED</option></select></label><label>Комментарий<textarea name="comment" minLength={3} maxLength={1000} required placeholder="Что получено и почему цикл можно закрыть" /></label><button type="submit" disabled={closureStatus === "submitting"}>{closureStatus === "submitting" ? "Записываю…" : "Подтвердить закрытие"}</button></form>{closureMessage && <p className={`closure-message ${closureStatus}`}>{closureMessage}</p>}</section></div>}
    <footer><div><span>EP</span><p>Elephant Pants · business system</p></div><p>EP-DP v0.2.1 · INTERNAL_QA / NOT_RELEASED</p><button onClick={() => go("service")}>Служебный раздел →</button></footer>
  </main>;
}
